name: rivermonitor
base: core20
version: '0.7'
summary: Retrieve river measurement data from USGS
description: River Monitor retrieves data from USGS Water Services and controls connected devices in response to measurements.
grade: devel
confinement: devmode
architectures: 
  - build-on: [amd64, arm64, armhf]
    run-on: [amd64, arm64, armhf]
parts:
  rivermonitor:
    plugin: dump
    source: rivermonitor-$SNAPCRAFT_PROJECT_VERSION-$SNAPCRAFT_TARGET_ARCH.tar.gz
apps:
  rivermonitor:
    command: ./rivermonitor